set gLaunchParam to 0.6.//0.55.
set gLaunchDuration to 245.66.
set gLaunchAngle to 17.33.
//set gLandingPA to -61.596.
set gShipRadius to 10.
//set SteeringManager:PitchPID:KI to 0.05.
//set SteeringManager:YawPID:KI to 0.05.
set SteeringManager:MaxStoppingTime to 5.
set params["rcsPower"] to 9.
